#include <stdio.h>
#include <stdlib.h> /* exit functions */
#include <unistd.h> /* read, write, pipe, _exit */
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h> /* wait */
#include <fcntl.h>
#include<time.h>

int main(int argc, char *argv[]){
    printf("I am %d \n", getpid());

    int n,i;
    int p1[2]; // p1 for child to parent (C => P) and
    int p2[2]; // p2 for parent to child (P => C)
    if (pipe(p1)== -1){return 1;}
    if (pipe(p2)== -1){ return 1;}
    //printf("Enter the number of processes\n");
    //scanf("%d",&n);

        pid_t pid = fork();

        if (pid == -1) { printf("An error ocurr when forkig \n"); }
        if (pid == 0) {
            time_t t;
            srand((unsigned int) t);
            printf("I am son %d \n", getpid());
            //child process
            close(p1[0]);
            close(p2[1]);
            int *num = (int *) malloc(sizeof(int));
            int Tab[2];

            //printf("Enter a number: \n");
            printf("J'attend que mon pere m'envoie une taille de %zu: \n", sizeof(num));
            if ((read(p2[0], num, sizeof(num)) == -1)) {
                printf("Pere n'as rien envoyer \n");
                return 2;
            } //reading data ggenerated by the father
            printf("Pere a envoyer: %d \n", num[1]);
            int numero = rand() % 999;
            printf("Je suis le fils et mon numero est: %d \n", numero);
            if (num[1] > numero) {
                //printf("");
                printf("Son Recieved %d from pid: %d\n", num[1], num[0]);
                printf("I've generate: %d\n", numero);
                if (write(p1[1], num, sizeof(num)) ==
                    -1) { return 2; } //write the received data if the previous generated number is greater than the new one
                printf("Wrote %d into the pipe by pid: %d \n", num[1], num[0]);
            } else {
                Tab[0] = getpid();
                Tab[1] = numero;
                if (write(p1[1], Tab, sizeof(Tab)) ==
                    -1) { return 2; } //write the new data if the previous generated number is lower than the new one
                printf(" Son Wrote %d into the pipe from pid: %d\n", Tab[1], Tab[0]);
            }


            close(p1[1]);
            close(p2[0]);

        } else {
            //parent process
            time_t t;
            srand((unsigned int) t);
            printf("I am parent writing %d \n", getpid());
            close(p1[1]);
            close(p2[0]);
            int number = rand() % 999;
            int Tab[2];
            int *Recv = (int *) malloc(sizeof(int)); //the table which will content the received values
            Tab[0] = getpid();
            Tab[1] = number;
            printf("Moi le pere, j'envoie une taille de %zu: \n", sizeof(Tab)); //verified if the data is send properly
            printf("Pere envoie un pointeur Tab :%p\n", Tab);
            if ((write(p2[1], Tab, sizeof(Tab)) == -1)) {
                printf("Je n'ai pas pu envoyer en tant que pere \n");
                return 2;
            }
            printf("Pere Wrote %d with the pid: %d\n", Tab[1], Tab[0]);
            if (read(p1[0], Recv, sizeof(Recv)) == -1) { return 2; }
            printf("The Result is: %d and i've received it from %d\n", Recv[1], Recv[0]);
            //printf("got number from %d :\n", Recv[0]);
            close(p1[0]);
            close(p2[1]);
            wait(NULL); /* wait for child to exit */
        }

    return 0;
}